export PATH="/Applications/CMake.app/Contents/bin":"$PATH"
export PATH="~/.platformio/penv/bin/":"$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(/usr/local/bin/rosetta-brew shellenv)"
. "$HOME/.cargo/env"
